version: "3"
services:
  sample:
    build: ../.
    volumes:
      - ../../.:/root/ros2_ws/src/sample
    environment:
      - DISPLAY=host.docker.internal:0.0
    network_mode: host
    privileged: true
    tty: true
