version: "3"
services:
  <your_service_name>:
    build: .
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/root/ros2_ws/src/<your_package>
    environment:
      - DISPLAY=:0
    network_mode: host
    privileged: true
    tty: true
